server:
  port: ${SERVER_PORT:9093}
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/db_oe-user-management
      username: postgres
      password: root
      maximum-pool-size: 5
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          time_zone: "Europe/Minsk"
      org:
        hibernate:
          envers:
            track_entities_changed_in_revision: true
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.hibernate: INFO