url:
  catalog: ${CATALOG_HOST:http://localhost}:${CATALOG_PORT:9090}
  inventory: ${INVENTORY_HOST:http://localhost}:${INVENTORY_PORT:9091}
server:
  port: ${SERVER_PORT:9092}
logging:
  level:
    ROOT: INFO
    org.springframework: INFO